#!/bin/bash

function firefox {
 show_info 'Removing unused pre-installed applications...'
 show_warning 'Requires root privileges'
 sudo apt purge -y firefox firefox-dbg firefox-dev firefox-launchpad-plugin firefox-locale-en firefox-locale-ru
 # Done
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Removal complete." 8 78
 cleanup
}
