#!/bin/bash

# System Animation on
function on {
    show_info 'Turn on the system animation...'
    gsettings set org.gnome.desktop.interface enable-animations true
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
    configure
}

# System Animation off
function off {
    show_info 'Turn off the system animation...'
    gsettings set org.gnome.desktop.interface enable-animations false
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
    configure
}

# Enable animations
function animations {
    eval `resize`
    ANIM=$(whiptail \
        --notags \
        --title "Enable/disable animations" \
        --menu "\nWhat would you like to do?" \
        --ok-button "Apply" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        on        'System Animation on' \
        off       'System Animation off' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $ANIM
    else
        clear && main
    fi
}
