#!/bin/bash

#Button-layout from left
function left {
    show_info 'Installation on the left edge...'
    gsettings set org.gnome.desktop.wm.preferences button-layout "close,maximize,minimize:"
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
    configure
}

#Button-layout from right
function right {
    show_info 'Installation on the right edge...'
    gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
    configure
}

# Button-layout
function button-layout {
    eval `resize`
    BUTTON=$(whiptail \
        --notags \
        --title "Button layout" \
        --menu "\nWhat would you like to do?" \
        --ok-button "Apply" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        left        'Location on the left edge' \
        right       'Location on the right edge' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $BUTTON
    else
        clear && main
    fi
}
