#!/bin/bash

# Xorg
function xorg {
    sudo renice -n -5 $(pidof X)
	# Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
    speedup
}

# tmp on tmpfs
function tmpfs {
	show_info 'Disabling apport crash dialogs...'
    show_warning 'Requires root privileges'
	echo "tmpfs /tmp tmpfs rw,nosuid,nodev 0 0" | sudo tee -a /etc/fstab
    # Reboot
    show_info 'Rebooting in 1 minute...'
    show_warning 'Save all files and exit the program!'
    sudo shutdown -r +1
	# Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Settings changed successfully." 8 78
    speedup
}
# Speed up system
function speedup {
    eval `resize`
    CONF=$(whiptail \
        --notags \
        --title "Speed up system" \
        --menu "\nWhat would you like to do?" \
        --ok-button "Apply" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        xorg        'Xorg' \
        tmpfs       'tmp on tmpfs (need reboot)' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $CONF
    else
        clear && main
    fi
}
