#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party/theme/adapta
source $dir/functions/third-party/theme/paper-icon
source $dir/functions/third-party/theme/placmank

# Install Third-Party Theme
function thirdparty-theme {
    eval `resize`
    THIRDPARTYTHEME=$(whiptail \
        --notags \
        --title "Third-Party Installation" \
        --menu "\nWhat third-party theme would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        adapta          'Adapta theme on Material Design' \
        paper-icon      'Paper icon theme' \
        placmank        'Placmank theme for Plank' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $THIRDPARTYTHEME
    else
        clear && main
    fi
}
