#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party/bleachbit
source $dir/functions/third-party/brackets
source $dir/functions/third-party/darktable
source $dir/functions/third-party/docky
source $dir/functions/third-party/dropbox
source $dir/functions/third-party/enpass
source $dir/functions/third-party/filezilla
source $dir/functions/third-party/firefox
source $dir/functions/third-party/fontforge
source $dir/functions/third-party/formatjunkie
source $dir/functions/third-party/gimp
source $dir/functions/third-party/gnome
source $dir/functions/third-party/google-chrome
source $dir/functions/third-party/gparted
source $dir/functions/third-party/grub-customizer
source $dir/functions/third-party/hudson
source $dir/functions/third-party/inkscape
source $dir/functions/third-party/java-jdk
source $dir/functions/third-party/jenkins
source $dir/functions/third-party/keepassx
source $dir/functions/third-party/krita
source $dir/functions/third-party/lamp
source $dir/functions/third-party/minecraft
source $dir/functions/third-party/mixxx
source $dir/functions/third-party/musicmanager
source $dir/functions/third-party/mypaint
source $dir/functions/third-party/notepadqq
source $dir/functions/third-party/obs-studio
source $dir/functions/third-party/opera
source $dir/functions/third-party/oracle-java
source $dir/functions/third-party/owncloud
source $dir/functions/third-party/peazip
source $dir/functions/third-party/plank
source $dir/functions/third-party/qbittorrent
source $dir/functions/third-party/rvm
source $dir/functions/third-party/sigil
source $dir/functions/third-party/simplescreenrecorder
source $dir/functions/third-party/slack
source $dir/functions/third-party/spotify
source $dir/functions/third-party/steadyflow
source $dir/functions/third-party/steam
source $dir/functions/third-party/sublime-text
source $dir/functions/third-party/teamviewer
source $dir/functions/third-party/telegram
source $dir/functions/third-party/textadept
source $dir/functions/third-party/tor
source $dir/functions/third-party/ubuntu-tweak
source $dir/functions/third-party/uget
source $dir/functions/third-party/umake
source $dir/functions/third-party/virtualbox
source $dir/functions/third-party/vocal
source $dir/functions/third-party/wine
source $dir/functions/third-party/wireshark
source $dir/functions/third-party/wps

# Install Third-Party Applications
function thirdparty {
    eval `resize`
    THIRDPARTY=$(whiptail \
        --notags \
        --title "Third-Party Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'dropbox'           'Dropbox' \
        'gnome'             'Latest GNOME desktop' \
        'google-chrome'     'Google Chrome' \
        'minecraft'         'Minecraft' \
        'oracle-java'       'Oracle Java 8' \
        'owncloud'          'ownCloud client' \
        'rvm'               'Ruby Version Manager (RVM)' \
        'slack'             'Slack' \
        'spotify'           'Spotify' \
        'steam'             'Steam' \
        'sublime-text'      'Sublime Text 3' \
        'vocal'             'Vocal podcast app' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $THIRDPARTY
    else
        clear && main
    fi
}

