#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party-data/thirdparty-theme-data/cursor
source $dir/functions/third-party-data/thirdparty-theme-data/icon
source $dir/functions/third-party-data/thirdparty-theme-data/plank
source $dir/functions/third-party-data/thirdparty-theme-data/theme

# Install Third-Party Theme
function thirdparty-theme {
    eval `resize`
    THIRDPARTYTHEME=$(whiptail \
        --notags \
        --title "Third-Party Installation" \
        --menu "\nWhat third-party theme would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        cursor          'Third-Party cursor theme' \
        icon            'Third-Party icon theme' \
        plank           'Third-Party theme for Plank' \
        theme           'Third-Party theme' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $THIRDPARTYTHEME
    else
        clear && main
    fi
}
