#!/bin/bash

# BleachBit
function bleachbit {
    # Add repository
    case `lsb_release -cs` in
	    wily)
       show_info 'Downloading BleachBit...'
	     curl -O https://download.bleachbit.org/bleachbit_1.10_all_ubuntu1510.deb
	        ;;
	    vivid)
       show_info 'Downloading BleachBit...'
	     curl -O https://download.bleachbit.org/bleachbit_1.10_all_ubuntu1504.deb
	        ;;
	    trusty)
       show_info 'Downloading BleachBit...'
	     curl -O https://download.bleachbit.org/bleachbit_1.10_all_ubuntu1404.deb
	        ;;
	    utopic)
       show_info 'Downloading BleachBit...'
	     curl -O https://download.bleachbit.org/bleachbit_1.10_all_ubuntu1410.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing BleachBit...'
	show_warning 'Requires root privileges'
	sudo dpkg -i bleachbit*.deb
	sudo apt-get install -fy
	# Cleanup and finish
	rm bleachbit*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
