#!/bin/bash

# Terminator
function gnome-terminator {
  # Add repository
  show_info 'Adding Terminator PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:gnome-terminator
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
	show_info 'Installing Terminator...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y terminator
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
