#!/bin/bash

# Terminix
function terminix {
  # Install dependencies
  show_info 'Installing Terminix dependencies...'
  show_warning 'Requires root privileges'
  sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
  sudo apt-get update
  sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
  sudo apt-get update
  sudo apt-get install dub
  show_info 'Downloading Terminix...'
  git clone https://github.com/gnunn1/terminix.git
  cd terminix
  dub build --build=release
  chmod +x install.sh
  # Install package(s)
  show_info 'Installing Terminix...'
  sudo ./install.sh
  # Back
  cd -
  # Cleanup and finish
  rm -rf terminix
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
