#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party-data/font-data/roboto

#
function font {
    eval `resize`
    FONT=$(whiptail \
        --notags \
        --title "" \
        --menu "\nWhat would you like to do?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        roboto        'Install Roboto font' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $FONT
    else
        clear && main
    fi
}
