#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party-data/thirdparty-theme-data/icon-data/paper-icon

# Install Third-Party Theme
function icon {
    eval `resize`
    ICON=$(whiptail \
        --notags \
        --title "Third-Party Installation" \
        --menu "\nWhat third-party theme would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        paper-icon      'Paper icon theme' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $ICON
    else
        clear && main
    fi
}
