#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party-data/thirdparty-theme-data/theme-data/adapta-theme
source $dir/functions/third-party-data/thirdparty-theme-data/theme-data/arc-theme
source $dir/functions/third-party-data/thirdparty-theme-data/theme-data/flat-plat-theme
source $dir/functions/third-party-data/thirdparty-theme-data/theme-data/paper-theme
source $dir/functions/third-party-data/thirdparty-theme-data/theme-data/white-theme

# Install Third-Party Theme
function theme {
    eval `resize`
    THEME=$(whiptail \
        --notags \
        --title "Third-Party Installation" \
        --menu "\nWhat third-party theme would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        adapta-theme     'Adapta theme on Material Design' \
        arc-theme        'ARC-theme a flat theme with transparent elements' \
        flat-plat-theme  'Flat-Plat theme on Material Design' \
        paper-theme      'Paper theme on Material Design' \
        white-theme      'White theme on Mac OS X Yosemite and El Capitan clean interface' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $THEME
    else
        clear && main
    fi
}
