#!/bin/bash

# Adapta
function adapta-theme {
  # Add repository
  show_info 'Adding Adapta PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:tista/adapta
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Adapta...'
  show_warning 'Requires root privileges'
  sudo apt install -y adapta-gtk-theme
  # Backup gnome-shell-theme.gresource
  sudo cp /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.backup
  sudo cp /usr/share/themes/Adapta/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell
  #sudo rm /usr/share/gnome-shell/gnome-shell-theme.gresource
  #sudo mv -f /usr/share/gnome-shell/gnome-shell-theme.gresource.backup /usr/share/gnome-shell/gnome-shell-theme.gresource
  # Apply
  show_info 'Apply Theme...'
  gsettings set org.gnome.desktop.interface gtk-theme 'Adapta'
  gsettings set org.gnome.shell.extensions.user-theme name 'Adapta'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
}
