#!/bin/bash

# ARC-theme
function arc-theme {
  # Add repository
	show_info 'Adding ARC-theme repository to software sources...'
	show_warning 'Requires root privileges'
	sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /' >> /etc/apt/sources.list.d/arc-theme.list"
	show_question 'Adding repository key...'
	show_warning 'Requires root privileges'
	wget http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key
  sudo apt-key add - < Release.key
	show_success 'Done.'
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing ARC-theme...'
  show_warning 'Requires root privileges'
  sudo apt install -y arc-theme
  # Apply
  show_info 'Apply Theme...'
  gsettings set org.gnome.desktop.interface gtk-theme 'Arc'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
}
