#!/bin/bash

# White Theme
function white-theme {
  show_info 'Downloading White Theme...'
	curl -O http://gnome-look.org/CONTENT/content-files/173840-White-Feb2016.tar.gz
	# Extraction package(s)
  show_info 'Extraction White Theme...'
  tar -xvf 173840-White-Feb2016.tar.gz
  # Install package(s)
  show_info 'Installing White Theme...'
  show_warning 'Requires root privileges'
  sudo cp -R ./White/ /usr/share/themes/
  sudo chmod -R 755 /usr/share/themes/White
  # Cleanup and finish
  rm 173840-White-Feb2016.tar.gz
  # Apply
  show_info 'Apply Theme...'
  gsettings set org.gnome.desktop.interface gtk-theme 'White'
  gsettings set org.gnome.shell.extensions.user-theme name 'White'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
}
