#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party-data/de-data/gnome
source $dir/functions/third-party-data/de-data/kde

# Install third-party-data Applications
function de {
    eval `resize`
    DE=$(whiptail \
        --notags \
        --title "third-party-data Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'gnome'             'Latest GNOME desktop' \
        'kde'               'Latest KDE desktop' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $DE
    else
        clear && main
    fi
}
