#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party-data/driver-data/hplip
source $dir/functions/third-party-data/driver-data/intel
source $dir/functions/third-party-data/driver-data/nvidia

# Install third-party-data Applications
function driver {
    eval `resize`
    DRIVER=$(whiptail \
        --notags \
        --title "third-party-data Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'hplip'             'HP Linux Imaging and Printing' \
        'intel'             'Intel Graphics Installer' \
        'nvidia'            'Nvidia Linux Display Driver' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $DRIVER
    else
        clear && main
    fi
}
