#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party-data/office-data/fontforge
source $dir/functions/third-party-data/office-data/font-manager
source $dir/functions/third-party-data/office-data/libreoffice
source $dir/functions/third-party-data/office-data/scribus
source $dir/functions/third-party-data/office-data/sigil
source $dir/functions/third-party-data/office-data/typecatcher
source $dir/functions/third-party-data/office-data/wpsoffice

# Install third-party-data Applications
function office {
    eval `resize`
    OFFICE=$(whiptail \
        --notags \
        --title "third-party-data Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'fontforge'         'FontForge' \
        'font-manager'      'Font manager' \
        'libreoffice'       'LibreOffice' \
        'scribus'           'Scribus' \
        'sigil'             'Sigil' \
        'typecatcher'       'Typecatcher' \
        'wps'               'WPS Office' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $OFFICE
    else
        clear && main
    fi
}
