#!/bin/bash

# OSX El Capitan X11 Mouse Theme
function mac-cursor {
  show_info 'Downloading OSX El Capitan X11 Mouse Theme...'
  wget --referer=https://dl.opendesktop.org/api/files/download/id/1461053384/175749-OSX-ElCap.tar.bz2 https://dl.opendesktop.org/api/files/download/id/1461053384/175749-OSX-ElCap.tar.bz2
  # Install package(s)
  show_info 'Installing OSX El Capitan X11 Mouse Theme...'
  tar -xvf 175749-OSX-ElCap.tar.bz2
  cd OSX-ElCap
  sudo ./install.sh
  # Cleanup and finish
  rm 175749-OSX-ElCap.tar.bz2
  # Apply
  show_info 'Apply Theme...'
  gsettings set org.gnome.desktop.interface cursor-theme 'OSX-ElCap'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
  }
