#!/bin/bash

# Font manager
function font-manager {
  # Add repository
  show_info 'Adding Font manager PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:font-manager/staging
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update
  # Install
  show_info 'Installing Font manager...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y font-manager
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
