#!/bin/bash

# Sigil
function sigil {
  # Add repository
  show_info 'Adding Sigil PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:rgibert/ebook
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update
  # Install
  show_info 'Installing Sigil...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y sigil
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
