#!/bin/bash

# WPS Office
function wpsoffice {
	show_info 'Downloading WPS Office...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_i386.deb
	        ;;
	    x86_64)
	        curl -O http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5503~a20p2_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  # Install package(s)
	show_info 'Installing WPS Office...'
	show_warning 'Requires root privileges'
	sudo dpkg -i wps-office*.deb
	sudo apt-get install -fy
	# Install dependencies
	show_info 'Installing WPS Office dependencies...'
	show_warning 'Requires root privileges'
	sudo apt-get install -y libc6 libfreetype6 libcups2 libglib2.0-0 libpng12-0 libglu1-mesa libsm6 libxrender1 libfontconfig1 libxext6 libxcb1
	# Cleanup and finish
	rm wps-office*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
