#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/purge

# Remove old kernels
function kernels {
    if (whiptail --title "Remove Outdated Kernels" --yesno "If you're not currently using the newest kernel installed on your system, the following may break it. \n\nAre you sure you want proceed?" 10 60) then
        show_info 'Removing outdated kernel(s)...'
        show_warning 'Requires root privileges'
        sudo dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | grep -v linux-libc-dev | xargs sudo apt -y purge
        show_success 'Done.'
        whiptail --title "Finished" --msgbox "Outdated kernels have been successfully removed." 8 78
        cleanup
    else
        clear && cleanup
    fi
}

# Remove Orphaned Packages
function orphaned {
 show_info 'Removing orphaned packages...'
 show_warning 'Requires root privileges'
 sudo apt -y autoremove
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Orphaned packages have been successfully removed." 8 78
 cleanup
}

function leftovers {
 show_info 'Removing leftover configuration files...'
 show_warning 'Requires root privileges'
 sudo dpkg --purge $(COLUMNS=200 dpkg -l | grep '^rc' | tr -s ' ' | cut -d ' ' -f 2)
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Leftover configuration files have been removed." 8 78
 cleanup
}

function clean-cache {
 show_info 'Cleaning package cache...'
 show_warning 'Requires root privileges'
 sudo apt -y clean
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Package cache has been cleaned." 8 78
 cleanup
}

# Remove old log crash
function crash {
 show_info 'Cleaning old log crash...'
 show_warning 'Requires root privileges'
 sudo rm /var/crash/*
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Old log crash has been cleaned." 8 78
 cleanup
}

# Terminal old command
function terminal-history {
 show_info 'Cleaning old log crash...'
 mv $HOME/.bash_history $HOME/.bash_history
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Old log crash has been cleaned." 8 78
 cleanup
}

# Cleanup System
function cleanup {
    eval `resize`
    CLEANUP=$(whiptail \
        --notags \
        --title "System Cleanup" \
        --menu "\nWhat would you like to do?" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        clean-cache 'Clean package cache' \
        leftovers   'Remove leftover configuration files' \
        orphaned    'Remove orphaned packages' \
        purge       'Remove unused pre-installed packages' \
        crash       'Remove old log crash' \
        kernels     'Remove old kernel(s)' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $CLEANUP
    else
        clear && main
    fi
}
