#!/bin/bash

dir="$(dirname "$0")"

source $dir/data/kernel/kernel-v4.14
source $dir/data/kernel/kernel-v4.15

# Kernel system upgrade
function kernel {
  eval `resize`
  KERNEL=$(whiptail \
    --notags \
    --title 'Update system kernel' \
    --menu '\nWhat would you like to do?' \
    --ok-button 'Update' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    kernel-v4.14 'Update 4.14 kernel' \
    kernel-v4.15 'Update 4.15 kernel' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $KERNEL
  else
    quit
  fi
}
