#!/bin/bash

# System Animation on
function on {
    show_info 'Включение системых анимаций...'
    gsettings set org.gnome.desktop.interface enable-animations true
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Настройки успешно изменены." 8 78
    configure
}

# System Animation off
function off {
    show_info 'Выключение системых анимаций...'
    gsettings set org.gnome.desktop.interface enable-animations false
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Настройки успешно изменены." 8 78
    configure
}

# Enable animations
function animations {
    eval `resize`
    ANIM=$(whiptail \
        --notags \
        --title "Включение/выключение анимаций" \
        --menu "\nЧем бы Вы хотели заняться?" \
        --ok-button "Применить" \
        --cancel-button "Назад" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        on        'Включить системные анимации' \
        off       'Выключить системные анимации' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $ANIM
    else
        clear && main
    fi
}
