#!/bin/bash

#Button-layout from left
function left {
    show_info 'Установка на левом краю...'
    gsettings set org.gnome.desktop.wm.preferences button-layout "close,maximize,minimize:"
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Настройки успешно изменены." 8 78
    configure
}

#Button-layout from right
function right {
    show_info 'Установка на правом краю...'
    gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Настройки успешно изменены." 8 78
    configure
}

# Button-layout
function button-layout {
    eval `resize`
    BUTTON=$(whiptail \
        --notags \
        --title "Расположение кнопок" \
        --menu "\nЧем бы Вы хотели заняться?" \
        --ok-button "Применить" \
        --cancel-button "Назад" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        left        'Установить расположение на левом краю' \
        right       'Установить расположение на правом краю' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $BUTTON
    else
        clear && main
    fi
}
