#!/bin/bash

dir="$(dirname "$0")"

DEPS="$dir/data/dependencies.list"

# Dependency Check
function check {
    show_info "Проверка зависимостей..."
    for package in $(cat $DEPS)
    do 
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $package|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        show_info "Этот сценарий использует '$package' , но он отсуствует нет в вашей системе."
        show_question 'Хотите установить, что бы продолжить? (Y)es, (N)o : ' && read REPLY
        echo ''
        case $REPLY in
        # Positive action
        [Yy]* ) 
            show_warning 'Требуется привилегии суперпользователя'
            sudo apt-get --force-yes --yes install $package
            show_success 'Готово.'
            main
            ;;
        # Negative action
        [Nn]* )
            show_info "Выход.."
            clear && exit 99
            ;;
        # Error
        * )
            clear && show_error '\aИзвините, попробуйте еще раз.' && check
            ;;
        esac
    else
        show_info "Все чисто."
    fi
    done
    
}
