#!/bin/bash

# Dependency Check
function check {
    show_info "Проверка зависимостей..."
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' whiptail|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        show_info "Этот сценарий использует 'whiptail', но он отсуствует нет в вашей системе.."
        show_question 'Хотите установить, что бы продолжить? (Y)es, (N)o : ' && read REPLY
        echo ''
        case $REPLY in
        # Positive action
        [Yy]* ) 
            show_warning 'Требуется привилегии суперпользователя'
            sudo apt-get --force-yes --yes install whiptail
            show_success 'Готово.'
            main
            ;;
        # Negative action
        [Nn]* )
            show_info "Выход.."
            clear && exit 99
            ;;
        # Error
        * )
            clear && show_error '\aИзвините, попробуйте еще раз.' && dependencies
            ;;
        esac
    else
        show_info "Все чисто."
    fi
}
