#!/bin/bash

dir="$(dirname "$0")"

PURGED="$dir/data/purge.list"

function unused {
    if (eval `resize` && whiptail \
        --title "Удаление предустановленных приложений" \
        --yesno "Текущий список предустановленных приложений для удаления: \n\n$(cat $PURGED) \n\nВы уверены, что хотите продолжить?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
        show_info 'Удаление предустановленных приложений...'
        show_warning 'Требуется привилегии суперпользователя'
        # Feel free to change the contents of 'utilities.list' in the data folder to whatever suits your preference.
        sudo apt-get remove -y $(cat $PURGED)
        # Done
        show_success 'Готово.'
        whiptail --title "Завершено" --msgbox "Удаление завершено." 8 78
        main
    else
        clear && main
    fi
}

# Remove old kernels
function kernels {
    if (whiptail --title "Удаление устаревших ядер" --yesno "Если вы не используете новейшие ядра, установленные в системе, следующие действие может удалить его.. \n\nВы уверены, что хотите продолжить?" 10 60) then
        show_info 'Удаление устаревших ядер...'
        show_warning 'Требуется привилегии суперпользователя'
        sudo dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | grep -v linux-libc-dev | xargs sudo apt-get -y purge
        show_success 'Готово.'
        whiptail --title "Завершено" --msgbox "Устаревшие ядра были успешно удалены." 8 78
        cleanup
    else
        clear && cleanup
    fi
}

# Remove Orphaned Packages
function orphaned {
    show_info 'Удаление ненужных пакетов...'
    show_warning 'Требуется привилегии суперпользователя'
    sudo apt-get autoremove -y
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Ненужные пакеты были успешно удалены." 8 78
    cleanup
}

function leftovers {
    show_info 'Удаление оставшихся файлов конфигурации...'
    show_warning 'Требуется привилегии суперпользователя'
    sudo dpkg --purge $(COLUMNS=200 dpkg -l | grep '^rc' | tr -s ' ' | cut -d ' ' -f 2)
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Оставшиеся файлы конфигурации были удалены." 8 78
    cleanup
}

function clean-cache {
    show_info 'Очистка кэша пакетов...'
    show_warning 'Требуется привилегии суперпользователя'
    sudo apt-get clean
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Кэш пакетов был очищен." 8 78
    cleanup
}

# Remove old log crash
function crash {
	show_info 'Очистка старых отчетов об ошибках...'
    show_warning 'Требуется привилегии суперпользователя'
	sudo rm /var/crash/*
	show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Отчеты об ошибках были очищены." 8 78
    cleanup	
}

# Cleanup System
function cleanup {
    eval `resize` 
    CLEANUP=$(whiptail \
        --notags \
        --title "Очистка системы" \
        --menu "\nЧем бы Вы хотели заняться?" \
        --cancel-button "Назад" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        clean-cache 'Очистить кеш пакетов' \
        leftovers   'Удалить оставшиеся файлы конфигураций' \
        orphaned    'Удалить ненужные пакеты' \
        unused      'Удалить предустановленные приложения' \
        crash       'Удалить старые отчеты об ошибках' \
        kernels     'Удалить старые ядра' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $CLEANUP
    else
        clear && main
    fi
}
