#!/bin/bash

# Install Ubuntu Restricted Extras
function codecs {
if (whiptail --title "Multimedia Codecs" --yesno "Install Ubuntu Restricted Extras for multimedia playback?" 10 60) then
    # Install Ubuntu Restricted Extras
    show_info 'Установка...'
    show_warning 'Требует привилегий суперпользователя'
    sudo apt-get install -y ubuntu-restricted-extras libavcodec-extra
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Установка завершена." 8 78
    main
else
    clear && main
fi
}
