#!/bin/bash

	# I
	case `echo sudo df -h` in
	    /)
	        
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;; 
	esac	


