#!/bin/bash

dir="$(dirname "$0")"

DEVTOOLS="$dir/data/development.list"

# Install Development Applications
function development {
    if (eval `resize` && whiptail \
        --title "Любимые инструменты разработки" \
        --yesno "Текущий список любимых инструментов разработки для установки: \n\n$(cat $DEVTOOLS) \n\nПродолжить установку?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext) then
        show_info 'Установка...'
        show_warning 'Требуется привилегии суперпользователя'
        # Feel free to change the contents of 'development.list' in the data folder to whatever suits your preference.
        sudo apt-get install -y $(cat $DEVTOOLS)
        # Done
        show_success 'Готово.'
        whiptail --title "Завершено" --msgbox "Установка завершена." 8 78
        main
    else
        clear && main
    fi
}
