#!/bin/bash

# Kernel stable
function stable {
if (whiptail --title "Обновление ядра системы" --yesno "Продолжить обновление ядра?" 10 60) then
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4-wily/linux-headers-4.4.0-040400-generic_4.4.0-040400.201601101930_i386.deb 
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4-wily/linux-headers-4.4.0-040400_4.4.0-040400.201601101930_all.deb 
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4-wily/linux-image-4.4.0-040400-generic_4.4.0-040400.201601101930_i386.deb
	        ;;
	    x86_64)
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4-wily/linux-headers-4.4.0-040400-generic_4.4.0-040400.201601101930_amd64.deb 
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4-wily/linux-headers-4.4.0-040400_4.4.0-040400.201601101930_all.deb 
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4-wily/linux-image-4.4.0-040400-generic_4.4.0-040400.201601101930_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;; 
	esac
    # Update repository information
    show_info 'Загрузка и установка...'
    show_warning 'Требуется привилегии суперпользователя'
    sudo dpkg -i linux-*.deb
    sudo apt-get install -fy
    # Grub-Update
    show_info 'Обновление конфигурации Grub...'
    sudo update-grub
    # Reboot
    show_info 'Перезагрузка...'
    sudo reboot
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Kernel update complete." 8 78
    main
else
    clear && main
fi
}

# Kernel unstable
function unstable {
if (whiptail --title "Обновить ядро системы" --yesno "Proceed with kernel update?" 10 60) then
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc1-wily/linux-headers-4.5.0-040500rc1-generic_4.5.0-040500rc1.201601241731_i386.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc1-wily/linux-headers-4.5.0-040500rc1_4.5.0-040500rc1.201601241731_all.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc1-wily/linux-image-4.5.0-040500rc1-generic_4.5.0-040500rc1.201601241731_i386.deb
	        ;;
	    x86_64)
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc1-wily/linux-headers-4.5.0-040500rc1-generic_4.5.0-040500rc1.201601241731_amd64.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc1-wily/linux-headers-4.5.0-040500rc1_4.5.0-040500rc1.201601241731_all.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc1-wily/linux-image-4.5.0-040500rc1-generic_4.5.0-040500rc1.201601241731_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;; 
	esac
    # Update repository information
    show_info 'Загрузка и установка...'
    show_warning 'Требуется привилегии суперпользователя'
    sudo dpkg -i linux-*.deb
    sudo apt-get install -fy
    # Grub-Update
    show_info 'Обновление конфигурации Grub...'
    sudo update-grub
    # Reboot
    show_info 'Перезагрузка...'
    sudo reboot
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Обновление ядра выполненно." 8 78
    main
else
    clear && main
fi
}

# Kernel system upgrade
function kernel {
    eval `resize`
    CONF=$(whiptail \
        --notags \
        --title "Обновление ядра системы" \
        --menu "\nЧем бы Вы хотели заняться?" \
        --ok-button "Обновить" \
        --cancel-button "Назад" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        stable        '(Обновить стабильную (v4.4-wily) версию (нужна перезагрузка)' \
        unstable      '(Обновить не стабильную (v4.5-rc1-wily) версию (нужна перезагрузка)' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $CONF
    else
        clear && main
    fi
}
