#!/bin/bash

# Kernel stable
function stable {
if (whiptail --title "Обновление ядра системы" --yesno "Продолжить обновление ядра?" 10 60) then
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.5-wily/linux-headers-4.4.5-040405-generic_4.4.5-040405.201603091931_i386.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.5-wily/linux-headers-4.4.5-040405_4.4.5-040405.201603091931_all.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.5-wily/linux-image-4.4.5-040405-generic_4.4.5-040405.201603091931_i386.deb
	        ;;
	    x86_64)
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.5-wily/linux-headers-4.4.5-040405-generic_4.4.5-040405.201603091931_amd64.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.5-wily/linux-headers-4.4.5-040405_4.4.5-040405.201603091931_all.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.5-wily/linux-image-4.4.5-040405-generic_4.4.5-040405.201603091931_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
    # Update repository information
    show_info 'Загрузка и установка...'
    show_warning 'Требуется привилегии суперпользователя'
    sudo dpkg -i linux-*.deb
    sudo apt-get install -fy
    # Grub-Update
    show_info 'Обновление конфигурации Grub...'
		show_warning 'Требуется привилегии суперпользователя'
    sudo update-grub
    # Cleanup and finish
  	rm linux-*.deb
    # Reboot
    show_info 'Перезагрузка, через 1 минуту...'
    show_warning 'Сохраните все файлы и завершите программы!'
    sudo shutdown -r +1
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Обновление ядра выполненно." 8 78
    main
else
    clear && main
fi
}

# Kernel unstable
function unstable {
if (whiptail --title "Обновить ядро системы" --yesno "Продолжить обновление ядра?" 10 60) then
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc7-wily/linux-headers-4.5.0-040500rc7-generic_4.5.0-040500rc7.201603061830_i386.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc7-wily/linux-headers-4.5.0-040500rc7_4.5.0-040500rc7.201603061830_all.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc7-wily/linux-image-4.5.0-040500rc7-generic_4.5.0-040500rc7.201603061830_i386.deb
	        ;;
	    x86_64)
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc7-wily/linux-headers-4.5.0-040500rc7-generic_4.5.0-040500rc7.201603061830_amd64.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc7-wily/linux-headers-4.5.0-040500rc7_4.5.0-040500rc7.201603061830_all.deb
	        curl -O http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.5-rc7-wily/linux-image-4.5.0-040500rc7-generic_4.5.0-040500rc7.201603061830_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
    # Update repository information
    show_info 'Загрузка и установка...'
    show_warning 'Требуется привилегии суперпользователя'
    sudo dpkg -i linux-*.deb
    sudo apt-get install -fy
    # Grub-Update
    show_info 'Обновление конфигурации Grub...'
		show_warning 'Требуется привилегии суперпользователя'
    sudo update-grub
    # Cleanup and finish
  	rm linux-*.deb
    # Reboot
    show_info 'Перезагрузка, через 1 минуту...'
    show_warning 'Сохраните все файлы и завершите программы!'
    sudo shutdown -r +1
    # Done
    show_success 'Готово.'
    whiptail --title "Завершено" --msgbox "Обновление ядра выполненно." 8 78
    main
else
    clear && main
fi
}

# Kernel system upgrade
function kernel {
    eval `resize`
    KERNEL=$(whiptail \
        --notags \
        --title "Обновление ядра системы" \
        --menu "\nЧем бы Вы хотели заняться?" \
        --ok-button "Обновить" \
        --cancel-button "Назад" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        stable        'Обновить стабильную (v4.4.5-wily) версию (нужна перезагрузка)' \
        unstable      'Обновить не стабильную (v4.5-rc7-wily) версию (нужна перезагрузка)' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $KERNEL
    else
        clear && main
    fi
}
