#!/bin/bash

# Perform system upgrade
function update {
if (whiptail --title "Обновление системы" --yesno "Proceed with system update?" 10 60) then
    # Update repository information
    show_info 'Обновление информации репозитория...'
    show_warning 'Требует привилегий суперпользователя'
    sudo apt-get update
    # Dist-Upgrade
    show_info 'Performing system update...'
    sudo apt-get dist-upgrade -y
    # Done
    show_success 'Готово.'
    whiptail --title "Finished" --msgbox "System update complete." 8 78
    main
else
    clear && main
fi
}
