#!/bin/bash

dir="$(dirname "$0")"

UTILS="$dir/data/utilities.list"

# Install Favourite System Utilities
function utilities {
    if (eval `resize` && whiptail --title \
        "Любимые системные утилиты"  --yesno \
        "Текущий список любимых системных утилит: \n\n$(cat $UTILS) \n\nПродолжить установку?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
        show_info 'Установка...'
        show_warning 'Требуется привилегии суперпользователя'
        # Feel free to change the contents of 'utilities.list' in the data folder to whatever suits your preference.
        sudo apt-get install -y --no-install-recommends $(cat $UTILS)
        # Done
        show_success 'Готово.'
        whiptail --title "Завершено" --msgbox "Установка завершена." 8 78
        main
    else
        clear && main
    fi
}
