#!/bin/bash

# Comix
function comix {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Comix...'
  show_warning 'Requires root privileges'
  sudo apt install -y comix
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
