#!/bin/bash

# GNOME mplayer
function gnome-mplayer {
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update
  # Install
  show_info 'Installing GNOME mplayer...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y gnome-mplayer
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
