#!/bin/bash

# Skype 4.3
function skype {
	sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing Skype...'
  show_warning 'Requires root privileges'
  sudo apt install -y skype
	sudo apt install gtk2-engines-murrine:i386 gtk2-engines-pixbuf:i386
	sudo apt install sni-qt:i386
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
