#!/bin/bash

# VLC
function vlc {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing VLC...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y vlc
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
