#!/bin/bash

# Chrome GNOME
function chrome-gnome-shell {
  # Add repository
  show_info 'Adding Chrome GNOME PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:ne0sight/chrome-gnome-shell
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Chrome GNOME...'
  show_warning 'Requires root privileges'
  sudo apt install -y chrome-gnome-shell
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
