#!/bin/bash

# Docky
function docky {
  # Add repository
  show_info 'Adding Docky PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:docky-core/stable
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Docky...'
  show_warning 'Requires root privileges'
  sudo apt install -y docky
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
