#!/bin/bash

# OBS studio
function obs-studio {
  # Add repository
  show_info 'Adding OBS studio PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:obsproject/obs-studio
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing OBS studio...'
  show_warning 'Requires root privileges'
  sudo apt install -y obs-studio
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
