#!/bin/bash

# Plank
function plank {
  # Add repository
  show_info 'Adding Plank PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo apt-add-repository -y ppa:docky-core/stable
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Plank...'
  show_warning 'Requires root privileges'
  sudo apt install -y plank
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
