#!/bin/bash

# TeamViewer
function teamviewer {
  # Downloading
  show_info 'Downloading TeamViewer...'
  case `uname -i` in
	    i386|i486|i586|i686)
	        wget https://downloadap1.teamviewer.com/download/version_11x/teamviewer_11.0.67687_i386.deb
	        ;;
	    x86_64)
	        wget https://downloadap1.teamviewer.com/download/version_11x/teamviewer_11.0.67687_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  # Install package(s)
  show_info 'Installing TeamViewer...'
  show_warning 'Requires root privileges'
  sudo dpkg -i teamviewer*.deb
  sudo dpkg --add-architecture i386
  sudo apt install -fy
  # Cleanup and finish
  rm teamviewer*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
