#!/bin/bash

# Variety
function variety {
  # Add repository
  show_info 'Adding Variety PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:peterlevi/ppa
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Variety...'
  show_warning 'Requires root privileges'
  sudo apt install -y variety
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
