#!/bin/bash

# Virtual Box
function virtualbox {
	# Add repository
	show_info 'Adding Virtual Box PPA repository to software sources...'
	show_warning 'Requires root privileges'
	sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian wily contrib" >> /etc/apt/sources.list.d/virtualbox.list'
	show_success 'Done.'
	show_question 'Adding repository key...'
	show_warning 'Requires root privileges'
	wget -q -O- https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add
	show_success 'Done.'
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing Virtual Box...'
	show_warning 'Requires root privileges'
	sudo apt install -y virtualbox-5.0
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
