#!/bin/bash

# Adapta
function adapta-theme {
  # Add repository
  show_info 'Adding Adapta PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:tista/adapta
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update
  # Install
  show_info 'Installing Adapta...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y adapta-gtk-theme
  # Apply
  show_info 'Apply Theme...'
  gsettings set org.gnome.desktop.interface gtk-theme 'Adapta'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
}
