#!/bin/bash

function evolution {
 show_info 'Removing unused pre-installed applications...'
 show_warning 'Requires root privileges'
 sudo apt-get purge -y evolution evolution-common evolution-data-server-dbg evolution-data-server-dev evolution-data-server-online-accounts evolution-dbg evolution-indicator evolution-plugins
 # Done
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Removal complete." 8 78
 cleanup
}
