#!/bin/bash

function imagemagick {
 show_info 'Removing unused pre-installed applications...'
 show_warning 'Requires root privileges'
 sudo apt-get purge -y imagemagick imagemagick-6.q16 imagemagick-dbg imagemagick-doc libmagick++-6.q16-5v5
 # Done
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Removal complete." 8 78
 cleanup
}
