#!/bin/bash

function rhythmbox {
 show_info 'Removing unused pre-installed applications...'
 show_warning 'Requires root privileges'
 sudo apt-get purge -y rhythmbox rhythmbox-ampache rhythmbox-data rhythmbox-dbg rhythmbox-dev rhythmbox-doc rhythmbox-mozilla rhythmbox-plugin-cdrecorder rhythmbox-plugin-magnatune rhythmbox-plugins rhythmbox-plugin-visualizer rhythmbox-plugin-zeitgeist rhythmbox-radio-browser
 # Done
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Removal complete." 8 78
 cleanup
}
