#!/bin/bash

# Nvidia Linux Display Driver
function nvidia {
  # Add repository
  show_info 'Adding Nvidia Linux Display Driver PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:graphics-drivers/ppa
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update
  # Install
  show_info 'Installing Nvidia Linux Display Driver...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y nvidia-367 nvidia-prime nvidia-settings
  # No logo
  show_info 'Uninstalling Nvidia logo...'
  show_warning 'Requires root privileges'
  sudo nvidia-xconfig --no-logo
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
