#!/bin/bash

# TeamViewer
function teamviewer {
  # Downloading
  show_info 'Downloading TeamViewer...'
  curl -O http://downloadap1.teamviewer.com/download/version_11x/teamviewer_11.0.57095_i386.deb
  # Install package(s)
  show_info 'Installing TeamViewer...'
  show_warning 'Requires root privileges'
  sudo dpkg -i teamviewer*.deb
  sudo apt-get install -fy
  # Cleanup and finish
  rm teamviewer*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
