#!/bin/bash

# Launchpad PPA tools
function launchpad {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing Launchpad PPA tools...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y dput devscripts dh-make debhelper
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
