#!/bin/bash

# Mixxx
function mixxx {
  # Add repository
  show_info 'Adding Mixxx PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:mixxx/mixxx
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing Mixxx...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y mixxx
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
