#!/bin/bash

# Nuvola player
function nuvolaplayer3 {


  sudo add-apt-repository "deb https://tiliado.eu/nuvolaplayer/repository/deb/ $(lsb_release -sc) stable"
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 40554B8FA5FE6F6A
  sudo apt-get update
  sudo apt-get install nuvolaplayer3





    # Add repository
    case `lsb_release -cs` in
	    wily)
	         show_info 'Adding Nuvola player PPA repository to software sources...'
	         show_warning 'Requires root privileges'
	         sudo sh -c 'echo "deb https://tiliado.eu/nuvolaplayer/repository/deb/ wily stable" >> /etc/apt/sources.list.d/tiliado-nuvolaplayer.list'
	         show_success 'Done.'
	         show_question 'Adding repository key...'
           show_warning 'Requires root privileges'
           sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 40554B8FA5FE6F6A
	         show_success 'Done.'
	        ;;
	    vivid)
	         show_info 'Adding Nuvola player PPA repository to software sources...'
	         show_warning 'Requires root privileges'
	         sudo sh -c 'echo "deb https://tiliado.eu/nuvolaplayer/repository/deb/ vivid stable" >> /etc/apt/sources.list.d/tiliado-nuvolaplayer.list'
	         show_success 'Done.'
	         show_question 'Adding repository key...'
           show_warning 'Requires root privileges'
           sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 40554B8FA5FE6F6A
	         show_success 'Done.'
	        ;;
	    trusty)
        	show_info 'Adding Nuvola player PPA repository to software sources...'
	        show_warning 'Requires root privileges'
	        sudo sh -c 'echo "deb https://tiliado.eu/nuvolaplayer/repository/deb/ trusty stable" >> /etc/apt/sources.list.d/tiliado-nuvolaplayer.list'
	        show_success 'Done.'
	        show_question 'Adding repository key...'
          show_warning 'Requires root privileges'
	        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 40554B8FA5FE6F6A
          show_success 'Done.'
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing Nuvola player...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y nuvolaplayer3
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
