#!/bin/bash

# Darktable
function darktable {
  # Add repository
  show_info 'Adding Darktable PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:pmjdebruijn/darktable-release
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Darktable...'
  show_warning 'Requires root privileges'
  sudo apt install -y darktable
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
