#!/bin/bash

# digiKam
function digikam {
  # Add repository
  show_info 'Adding digiKam PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:msylwester/digikam
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing digiKam...'
  show_warning 'Requires root privileges'
  sudo apt install -y digikam
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
