#!/bin/bash

# Gimp
function gimp {
  # Add repository
  show_info 'Adding Gimp PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Gimp...'
  show_warning 'Requires root privileges'
  sudo apt install -y gimp
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
