#!/bin/bash

# Inkscape
function inkscape {
	# Add repository
	show_info 'Adding Inkscape PPA to software sources...'
	show_warning 'Requires root privileges'
	sudo add-apt-repository -y ppa:inkscape.dev/stable
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing Inkscape...'
	show_warning 'Requires root privileges'
	sudo apt install -y inkscape
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
