#!/bin/bash

# Krita
function krita {
  # Add repository
  show_info 'Adding Krita PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:dimula73/krita
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Krita...'
  show_warning 'Requires root privileges'
  sudo apt install -y krita-2.9
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
