#!/bin/bash

# LightZone
function lightzone {
  # Add repository
  show_info 'Adding LightZone PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:otto-kesselgulasch/lightzone
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing LightZone...'
  show_warning 'Requires root privileges'
  sudo apt install -y lightzone
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
