#!/bin/bash

# Lightworks
function lightworks {
	show_info 'Downloading Lightworks...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://www.lwks.com/dmpub/lwks-12.5.0-i386.deb
	        ;;
	    x86_64)
	        curl -O http://www.lwks.com/dmpub/lwks-12.5.0-amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing Lightworks...'
	show_warning 'Requires root privileges'
	sudo dpkg -i lwks*.deb
	sudo apt install -fy
	# Cleanup and finish
	rm lwks*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
