#!/bin/bash

# Linaro
function linaro {
  # Add repository
  show_info 'Adding Linaro PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:linaro-maintainers/tools
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Linaro...'
  show_warning 'Requires root privileges'
  sudo apt install -y linaro-image-tools
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
