#!/bin/bash

# Photivo
function photivo {
  # Add repository
  show_info 'Adding Photivo PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:dhor/myway
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Photivo...'
  show_warning 'Requires root privileges'
  sudo apt install -y photivo
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
