#!/bin/bash

# Pinta
function pinta {
  # Add repository
  show_info 'Adding Pinta PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:pinta-maintainers/pinta-stable
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Pinta...'
  show_warning 'Requires root privileges'
  sudo apt install -y pinta
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
