#!/bin/bash

# Pixeluvo
function pixeluvo {
	show_info 'Downloading Pixeluvo...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://www.pixeluvo.com/downloads/pixeluvo_1.5.2-1_i386.deb
	        ;;
	    x86_64)
	        curl -O http://www.pixeluvo.com/downloads/pixeluvo_1.5.2-3_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing Pixeluvo...'
	show_warning 'Requires root privileges'
	sudo dpkg -i pixeluvo*.deb
	sudo apt install -fy
	# Cleanup and finish
	rm pixeluvo*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
