#!/bin/bash

# RawTherapee
function rawtherapee {
  # Add repository
  show_info 'Adding RawTherapee PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:dhor/myway
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing RawTherapee...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y rawtherapee
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
