#!/bin/bash

# Lubuntu-Box
function lubuntubox {
    # Add repository
    show_info 'Adding Lubuntu-Box to software sources...'
    show_warning 'Requires root privileges'
    sudo add-apt-repository -y ppa:noobslab/icons
	# Update repository information
	show_info 'Updating repository information...'
	sudo apt-get update
	# Install
    echo 'Installing Lubuntu-Box...'
    show_warning 'Requires root privileges'
    sudo apt-get install -y lubuntubox
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
