#!/bin/bash

# Blender
function blender {
  # Add repository
  show_info 'Adding Blender PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:thomas-schiex/blender
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Blender...'
  show_warning 'Requires root privileges'
  sudo apt install -y blender
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
