#!/bin/bash

# Formatjunkie
function formatjunkie {
  # Add repository
  show_info 'Adding Formatjunkie PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:format-junkie-team/release
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing Formatjunkie...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y formatjunkie
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
