#!/bin/bash

# GNOME MPV
function plank {
  # Add repository
  show_info 'Adding GNOME MPV PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo apt-add-repository -y ppa:xuzhen666/gnome-mpv
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update
  # Install
  show_info 'Installing GNOME MPV...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y gnome-mpv
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
