#!/bin/bash

# Kodi
function kodi {
  # Add repository
  show_info 'Adding Kodi PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:team-xbmc/ppa
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Kodi...'
  show_warning 'Requires root privileges'
  sudo apt install -y kodi kodi-pvr-mythtv
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
