#!/bin/bash

# Plex
function plex {
	show_info 'Downloading Plex...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O https://downloads.plex.tv/plex-media-server/0.9.15.3.1674-f46e7e6/plexmediaserver_0.9.15.3.1674-f46e7e6_i386.deb
	        ;;
	    x86_64)
	        curl -O https://downloads.plex.tv/plex-media-server/0.9.15.3.1674-f46e7e6/plexmediaserver_0.9.15.3.1674-f46e7e6_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing Plex...'
	show_warning 'Requires root privileges'
	sudo dpkg -i plexmediaserver*.deb
	sudo apt install -fy
	# Cleanup and finish
	rm plexmediaserver*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
