#!/bin/bash

# Shotcut
function shotcut {
  # Add repository
  show_info 'Adding Shotcut PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:haraldhv/shotcut
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Shotcut...'
  show_warning 'Requires root privileges'
  sudo apt install -y shotcut
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
