#!/bin/bash

# GNOME
function gnome {
  # Add repository
  show_info 'Adding GNOME3 PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:gnome3-team/gnome3-staging
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Dist-Upgrade
  show_info 'Performing system update...'
  show_warning 'Requires root privileges'
  sudo apt -y full-upgrade
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
