#!/bin/bash

# KDE
function kde {
  # Add repository
  show_info 'Adding KDE PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:kubuntu-ppa/backports
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt-get update
	## Install
  #show_info 'Installing KDE Desktop...'
  #show_warning 'Requires root privileges'
  #sudo apt-get install -y kde-plasma-desktop dolphin karchive
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
