#!/bin/bash

# MATE
function mate {
  # Add repository
  show_info 'Adding MATE PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:samoilov-lex/mate-stable
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Dist-Upgrade
  show_info 'Performing system update...'
  show_warning 'Requires root privileges'
  sudo apt -y dist-upgrade
  # Install
  #show_info 'Installing MATE Desktop...'
  #show_warning 'Requires root privileges'
  #sudo apt install -y 
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
