#!/bin/bash

# Opera
function opera {
  show_info 'Downloading Opera...'
  # Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://download1.operacdn.com/pub/opera/desktop/36.0.2130.65/linux/opera-stable_36.0.2130.65_i386.deb
	        ;;
	    x86_64)
	        curl -O http://download1.operacdn.com/pub/opera/desktop/36.0.2130.65/linux/opera-stable_36.0.2130.65_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  # Install package(s)
  show_info 'Installing Opera...'
  show_warning 'Requires root privileges'
  sudo dpkg -i opera*.deb
  sudo apt-get install -fy
  # Cleanup and finish
  rm opera*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
