#!/bin/bash

# Telegram
function telegram {
  show_info 'Downloading Telegram...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O https://updates.tdesktop.com/tlinux32/tsetup32.0.9.49.tar.xz
	        ;;
	    x86_64)
	        curl -O https://updates.tdesktop.com/tlinux/tsetup.0.9.49.tar.xz
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  show_info 'Extraction Telegram...'
  tar -xJvf tsetup*.tar.xz
	# Install lang(s)
	case `echo $LANG` in
	    ru_RU.UTF-8)
	        curl -O https://tlgrm.ru/files/locales/tdesktop/Russian.strings
	        ;;
	    uk_UA.UTF-8)
	        curl -O https://tlgrm.ru/files/locales/tdesktop/Ukrainian.strings
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  mv *.strings ./Telegram
  # Install package(s)
  show_info 'Installing Telegram...'
  show_warning 'Requires root privileges'
  sudo mv ./Telegram /opt/telegram
  # Create symbolic link
  #show_info 'Creating symbolic link...'
  #show_warning 'Requires root privileges'
  #sudo ln -sf /opt/telegram/Telegram /usr/bin
  # Cleanup and finish
  rm tsetup*.tar.xz
  # Create icon desktop and starting
  #Telegram
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
