#!/bin/bash

# XAMPP
function xampp {
  show_info 'Downloading XAMPP...'
  # Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O https://www.apachefriends.org/xampp-files/7.0.5/xampp-linux-7.0.5-0-installer.run
	        ;;
	    x86_64)
	        curl -O https://www.apachefriends.org/xampp-files/7.0.5/xampp-linux-x64-7.0.5-0-installer.run
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  # Set Permission File
  show_info 'Set Permission File...'
  show_warning 'Requires root privileges'
  sudo chmod +x xampp*.run
  # Install
  show_info 'Installing XAMPP...'
  show_warning 'Requires root privileges'
  ./xampp*.run
  # Cleanup and finish
  rm xampp*.run
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
