#!/bin/bash

# Placmank plank theme
function placmank-plank {
  # Add repository
  show_info 'Adding Placmank PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:dyatlov-igor/placmank
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Placmank...'
  show_warning 'Requires root privileges'
  sudo apt install -y placmank
  plank --preferences
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
}
