#!/bin/bash

# Placmank
function placmank-plank {
  # Add repository
  show_info 'Adding Placmank PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:dyatlov-igor/placmank
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update
  # Install
  show_info 'Installing Placmank...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y placmank
  # Apply
  show_info 'Apply Theme...'
  gsettings set /net/launchpad/plank/docks/dock1/theme 'Placmank'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
}
