#!/bin/bash

# Natron
function natron {
	show_info 'Downloading Natron...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://downloads.natron.fr/Linux/releases/32bit/files/natron_2.0.0.RC6-2_i386.deb
	        ;;
	    x86_64)
	        curl -O http://downloads.natron.fr/Linux/releases/64bit/files/natron_2.0.0.RC6-2_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing Natron...'
	show_warning 'Requires root privileges'
	sudo dpkg -i natron*.deb
	sudo apt-get install -fy
	# Cleanup and finish
	rm natron*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
