#!/bin/bash

# Cinelerra
function cinelerra {
  # Add repository
  show_info 'Adding Cinelerra PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:cinelerra-ppa/ppa
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Cinelerra...'
  show_warning 'Requires root privileges'
  sudo apt install -y cinelerra-cv
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
