#!/bin/bash

# Clementine
function clementine {
  # Add repository
  show_info 'Adding Clementine PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:me-davidsansome/clementine
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Clementine...'
  show_warning 'Requires root privileges'
  sudo apt install -y clementine
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
