#!/bin/bash

# Hydrogen
function hydrogen {
  # Add repository
  show_info 'Adding Hydrogen PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:kxstudio-team/hydrogen
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Hydrogen...'
  show_warning 'Requires root privileges'
  sudo apt install -y hydrogen
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
