#!/bin/bash

# Quod Libet
function quodlibet {
  # Add repository
  show_info 'Adding Quod Libet PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:lazka/ppa
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Quod Libet...'
  show_warning 'Requires root privileges'
  sudo apt install -y quodlibet
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
