#!/bin/bash

# Rhythmbox
function rhythmbox {
  # Add repository
  show_info 'Adding Rhythmbox PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:fossfreedom/rhythmbox ppa:fossfreedom/rhythmbox-plugins
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
	show_info 'Installing Rhythmbox...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y rhythmbox rhythmbox-plugin-complete rhythmbox-plugin-equalizer rhythmbox-plugin-coverart-browser
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
