#!/bin/bash

# Chromium
function chromium {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing Chromium...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y chromium-browser chromium-browser-l10n
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
