#!/bin/bash

# Skype 4.3
function skype {
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
	show_info 'Installing Skype...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y skype

  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}


sudo apt install gtk2-engines-murrine:i386 gtk2-engines-pixbuf:i386
sudo apt-get install sni-qt:i386
