#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party-data/security-data/drweb
source $dir/functions/third-party-data/security-data/enpass
source $dir/functions/third-party-data/security-data/gufw
source $dir/functions/third-party-data/security-data/keepassx

# Install third-party-data Applications
function security {
    eval `resize`
    SECURITY=$(whiptail \
        --notags \
        --title "third-party-data Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'drweb'             'Dr.Web CureIt!' \
        'enpass'            'Enpass Password manager' \
        'gufw'              'Gufw' \
        'keepassx'          'KeePassX Password manager' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $SECURITY
    else
        clear && main
    fi
}
