#!/bin/bash

# Peazip
function peazip {
	show_info 'Downloading Peazip...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://sourceforge.net/projects/peazip/files/5.9.1/peazip_5.9.1.LINUX.GTK2-2_i386.deb
	        ;;
	    x86_64)
	        curl -O http://sourceforge.net/projects/peazip/files/5.9.1/peazip_5.9.1.LINUX.GTK2-2_all.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing Peazip...'
	show_warning 'Requires root privileges'
	sudo dpkg -i peazip*.deb
	sudo apt install -fy
	show_info 'Downloading dependent 32-bit libraries...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    x86_64)
	        sudo apt install -y libatk1.0-0:i386 libc6:i386 libcairo2:i386 libgdk-pixbuf2.0-0:i386 libglib2.0-0:i386 libgtk2.0-0:i386 libpango1.0-0:i386 libx11-6:i386 libcanberra-gtk-module:i386
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Cleanup and finish
	rm peazip*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
