#!/bin/bash

# tlp
function tlp {
  # Add repository
  show_info 'Adding tlp PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:linrunner/tlp
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing tlp...'
  show_warning 'Requires root privileges'
  sudo apt install -y tlp tlp-rdw
  show_info 'Start tlp...'
  sudo tlp start
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
