#!/bin/bash

# Numix Circle Icon Theme
function numix-circle-icon {
  # Add repository
  show_info 'Adding Numix PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:numix/ppa
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Numix Circle...'
  show_warning 'Requires root privileges'
  sudo apt install -y numix-icon-theme-circle
  # Apply
  show_info 'Apply Icon Theme...'
  gsettings set org.gnome.desktop.interface icon-theme 'Numix-Circle'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
}
