#!/bin/bash

# LAMP
function lamp {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing LAMP...'
	show_warning 'Requires root privileges'
	sudo apt install -y apache2 php5 mysql-server mysql-client php5-mysql phpmyadmin libapache2-mod-php5
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
