#!/bin/bash

# Samba
function samba {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing Samba...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y samba system-config-samba gadmin-samba samba-common samba-common-bin samba-libs
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
