#!/bin/bash

# Geany
function geany {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Geany...'
  show_warning 'Requires root privileges'
  sudo apt install -y geany
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
