#!/bin/bash

# Gparted
function gparted {
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Gparted...'
  show_warning 'Requires root privileges'
  sudo apt install -y gparted
  # Install dependencies
  show_info 'Installing Gparted dependencies...'
  show_warning 'Requires root privileges'
  sudo apt install -y btrfs-tools e2fsprogs dosfstools hfsutils hfsutils-tcltk f2fs-tools hfsprogs jfsutils util-linux lvm2 ntfs-3g reiser4progs reiserfsprogs xfsprogs xfsdump
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
