#!/bin/bash

# Bluefish
function bluefish {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt-get update
	# Install
  show_info 'Installing Bluefish...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y bluefish bluefish-data bluefish-plugins
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
