#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/purge-data/audio-data/rhythmbox-purge


# Install third-party-data Applications
function audio-r {
    eval `resize`
    AUDIOR=$(whiptail \
        --notags \
        --title "third-party-data Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'rhythmbox-purge'         'Rhythmbox' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $AUDIOR
    else
        clear && main
    fi
}
