#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/purge-data/games-data/aisleriot
source $dir/functions/purge-data/games-data/gnome-mahjongg
source $dir/functions/purge-data/games-data/gnome-mines
source $dir/functions/purge-data/games-data/gnome-sudoku

# Install third-party-data Applications
function games-r {
    eval `resize`
    GAMESR=$(whiptail \
        --notags \
        --title "third-party-data Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'aisleriot'          'Aisleriot' \
        'gnome-mahjongg'     'Mahjongg' \
        'gnome-mines'        'Mines' \
        'gnome-sudoku'       'Sudoku' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $GAMESR
    else
        clear && main
    fi
}
