#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/purge-data/system-data/brasero
source $dir/functions/purge-data/system-data/deja-dup
source $dir/functions/purge-data/system-data/gnome-orca
source $dir/functions/purge-data/system-data/imagemagick
source $dir/functions/purge-data/system-data/landscape
source $dir/functions/purge-data/system-data/openjdk
source $dir/functions/purge-data/system-data/overlay-scrollbar
source $dir/functions/purge-data/system-data/telepathy
source $dir/functions/purge-data/system-data/zeitgeist

# Install third-party-data Applications
function system-r {
    eval `resize`
    SYSTEMR=$(whiptail \
        --notags \
        --title "third-party-data Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'brasero'               'brasero' \
        'deja-dup'              'deja-dup' \
        'gnome-orca'            'gnome-orca' \
        'imagemagick'           'imagemagick' \
        'landscape'             'landscape' \
        'openjdk'               'openjdk' \
        'overlay-scrollbar'     'overlay-scrollbar' \
        'telepathy'             'telepathy' \
        'zeitgeist'             'zeitgeist' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $SYSTEMR
    else
        clear && main
    fi
}
