#!/bin/bash

# Bitcoin
function bitcoin {
  # Add repository
  show_info 'Adding Bitcoin PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:bitcoin/bitcoin
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Bitcoin...'
  show_warning 'Requires root privileges'
  sudo apt install -y bitcoin-qt
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
