#!/bin/bash

# Cutegram
function cutegram {
  # Add repository
  show_info 'Adding Cutegram PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:aseman/desktop-apps
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Cutegram...'
  show_warning 'Requires root privileges'
  sudo apt install -y cutegram
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
