#!/bin/bash

# Google Chrome
function google-chrome {
eval `resize`
exitstatus=$?
if [ $exitstatus = 0 ]; then
    status="0"
    while [ "$status" -eq 0 ]
    do

        VERSION=$(whiptail \
        --title "Google Chrome" --radiolist \
        "Which version of Chrome would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        "stable"    "Stable builds" ON \
        "beta"      "Beta builds" OFF \
        "unstable"  "Unstable builds" OFF \
        3>&1 1>&2 2>&3)

        # Change to lower case and remove spaces.
        case "${VERSION}" in
            stable)
              # Add repository
	            show_info 'Adding Google Chrome PPA repository to software sources...'
	            show_warning 'Requires root privileges'
              # Download Debian file that matches system architecture
            	case `uname -i` in
            	    i386|i486|i586|i686)
                      show_info 'Remove Google Chrome...'
                      show_warning 'Requires root privileges'
                      sudo rm /etc/apt/sources.list.d/google-chrome.list
                      sudo apt purge google-chrome-stable
                      show_info 'Installing Chromium...'
                      show_warning 'Requires root privileges'
                      sudo apt install -y chromiulytm-browser chromium-browser-l10n
            	        ;;
            	    x86_64)
                      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
                      show_success 'Done.'
                      show_question 'Adding repository key...'
                      show_warning 'Requires root privileges'
                      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                      show_success 'Done.'
                      # Update repository information
                      show_info 'Updating repository information...'
                      show_warning 'Requires root privileges'
                      sudo apt update
                      # Install
                      show_info 'Installing Google Chrome...'
                      show_warning 'Requires root privileges'
                      sudo apt install -y google-chrome-stable
                      show_info 'Fixed Google Chrome...'
                      show_warning 'Requires root privileges'
            	        sudo sed -i -e 's/deb http/deb [arch=amd64] http/' "/opt/google/chrome/cron/google-chrome"
                      # Done
                      show_success 'Done.'
                      whiptail --title "Finished" --msgbox "Installation complete." 8 78
                      status=1
                      thirdparty
            	        ;;
            	    *)
            	        show_error "No packages available to download that matches your system." && thirdparty
            	        ;;
            	esac

	            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
	            show_success 'Done.'
	            show_question 'Adding repository key...'
              show_warning 'Requires root privileges'
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	            show_success 'Done.'
              # Update repository information
	            show_info 'Updating repository information...'
              show_warning 'Requires root privileges'
	            sudo apt update
              # Install
              show_info 'Installing Google Chrome...'
              show_warning 'Requires root privileges'
              sudo apt install -y google-chrome-stable
              # Install dependencies
	            show_info 'Installing Google Chrome dependencies...'
	            show_warning 'Requires root privileges'
	            sudo apt install -y libappindicator1 libindicator7
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              thirdparty
            ;;
            beta)
              # Add repository
	            show_info 'Adding Google Chrome PPA repository to software sources...'
	            show_warning 'Requires root privileges'
	            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
	            show_success 'Done.'
	            show_question 'Adding repository key...'
              show_warning 'Requires root privileges'
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	            show_success 'Done.'
              # Update repository information
	            show_info 'Updating repository information...'
              show_warning 'Requires root privileges'
	            sudo apt update
              # Install
              show_info 'Installing Google Chrome...'
              show_warning 'Requires root privileges'
              sudo apt install -y google-chrome-beta
              # Install dependencies
	            show_info 'Installing Google Chrome dependencies...'
	            show_warning 'Requires root privileges'
	            sudo apt install -y libappindicator1 libindicator7
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              thirdparty
            ;;
            unstable)
              # Add repository
	            show_info 'Adding Google Chrome PPA repository to software sources...'
	            show_warning 'Requires root privileges'
	            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
	            show_success 'Done.'
	            show_question 'Adding repository key...'
              show_warning 'Requires root privileges'
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	            show_success 'Done.'
              # Update repository information
	            show_info 'Updating repository information...'
              show_warning 'Requires root privileges'
	            sudo apt update
              # Install
              show_info 'Installing Google Chrome...'
              show_warning 'Requires root privileges'
              sudo apt install -y google-chrome-unstable
              # Install dependencies
	            show_info 'Installing Google Chrome dependencies...'
	            show_warning 'Requires root privileges'
	            sudo apt install -y libappindicator1 libindicator7
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              thirdparty
            ;;
            *) status=1
              thirdparty
            ;;
        esac
        exitstatus1=$status1
    done
else
    clear && thirdparty
fi
}
