#!/bin/bash

# Angry IP Scanner
function ipscan {
	show_info 'Downloading Angry IP Scanner...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O http://github.com/angryziber/ipscan/releases/download/3.4.1/ipscan_3.4.1_i386.deb
	        ;;
	    x86_64)
	        curl -O http://github.com/angryziber/ipscan/releases/download/3.4.1/ipscan_3.4.1_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing Angry IP Scanner...'
	show_warning 'Requires root privileges'
	sudo dpkg -i ipscan*.deb
	sudo apt-get install -fy
	# Cleanup and finish
	rm ipscan*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
