#!/bin/bash

# ownCloud
function owncloud {
	# Add repository
	show_info 'Adding ownCloud repository to software sources...'
	show_warning 'Requires root privileges'
	sudo sh -c 'echo "deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/" >> /etc/apt/sources.list.d/owncloud.list'
	show_success 'Done.'
	show_question 'Adding repository key...'
	show_warning 'Requires root privileges'
	curl -O http://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_14.04/Release.key | sudo apt-key add -
	show_success 'Done.'
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing ownCloud client...'
	show_warning 'Requires root privileges'
	sudo apt install -y owncloud-client
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
