#!/bin/bash

# Deluge
function deluge {
  # Add repository
  show_info 'Adding Deluge PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:deluge-team/ppa
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Deluge...'
  show_warning 'Requires root privileges'
  sudo sh -c 'echo "deb http://deb.torproject.org/torproject.org/ yakkety main" >> /etc/apt/sources.list.d/tor.list'
gpg --keyserver keys.gnupg.net --recv 886DDD89
gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
