#!/bin/bash

# Viber
function viber {
  show_info 'Downloading Viber...'
  # Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	    x86_64)
	        curl -O http://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  # Install package(s)
  show_info 'Installing Viber...'
  show_warning 'Requires root privileges'
  sudo dpkg -i viber*.deb
  sudo apt install -fy
  # Cleanup and finish
  rm viber*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
