#!/bin/bash

# Vivaldi
function vivaldi {
	show_info 'Downloading Vivaldi...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        wget https://download.vivaldi.com/stable/vivaldi-stable_1.0.435.40-1_i386.deb
	        ;;
	    x86_64)
	        wget https://download.vivaldi.com/stable/vivaldi-stable_1.0.435.40-1_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing Vivaldi...'
	show_warning 'Requires root privileges'
	sudo dpkg -i vivaldi*.deb
	sudo apt install -fy
	# Cleanup and finish
	rm vivaldi*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
