#!/bin/bash

# Wireshark
function wireshark {
  # Add repository
  show_info 'Adding Wireshark PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:dreibh/ppa
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Wireshark...'
  show_warning 'Requires root privileges'
  sudo apt install -y wireshark
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
