#!/bin/bash

# Android Studio
function android-studio {
  # Add repository
  show_info 'Adding Oracle Java 8 PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:webupd8team/java
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Oracle Java 8...'
  show_warning 'Requires root privileges'
  sudo apt install -y oracle-java8-installer
  # Install dependencies
  show_info 'Installing Java JDK dependencies...'
  show_warning 'Requires root privileges'
  sudo apt install -y lib32ncurses5 lib32ncurses5-dev libc6-i386 lib32stdc++6 lib32gcc1 lib32z1 lib32z1-dev
  show_info 'Downloading Android Studio...'
  wget https://dl.google.com/dl/android/studio/ide-zips/3.0.0.18/android-studio-ide-171.4408382-linux.zip
  show_info 'Extraction Android Studio...'
  unzip android-studio-ide*.zip
  # Create icon desktop
  show_info 'Create icon...'
  touch android-studio.desktop
  echo "[Desktop Entry]" >> android-studio.desktop
  echo "Encoding=UTF-8" >> android-studio.desktop
  echo "Version=1.0" >> android-studio.desktop
  echo "Type=Application" >> android-studio.desktop
  echo "Terminal=false" >> android-studio.desktop
  echo "Name=Android Studio" >> android-studio.desktop
  echo "Exec=$HOME/.local/share/android-studio/bin/studio.sh" >> android-studio.desktop
  echo "Comment=Integrated Android developer tools for development and debugging." >> android-studio.desktop
  echo "Icon=studio.png" >> android-studio.desktop
  # Or stok icon
  ########echo "Icon=/opt/android-studio/bin/studio.png" >> android-studio.desktop########
  echo "Categories=GNOME;GTK;Development;IDE;" >> android-studio.desktop
  # Set Permission File
  show_info 'Set Permission File...'
  show_warning 'Requires root privileges'
  sudo chmod +x android-studio.desktop
  sudo mv android-studio.desktop /usr/share/applications
  # Install package(s)
  show_info 'Installing Android Studio...'
  mv ./android-studio $HOME/.local/share/android-studio
  # Cleanup and finish
  rm android-studio-ide*.zip
  ## Give permessions to folder to let the built-in update system work
  show_info 'Set Permission folder...'
  find $HOME/.local/share/android-studio/ -type d -exec chmod 777 {} \;
  find $HOME/.local/share/android-studio/ -type f -exec chmod 777 {} \;
  # Set Permission File
  show_info 'Set Permission File...'
  cd $HOME/.local/share/android-studio/bin
  chmod +x studio.sh
  # Run
  ./studio.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
