#!/bin/bash

# Notepadqq
function notepadqq {
  # Add repository
  show_info 'Adding Notepadqq PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:notepadqq-team/notepadqq
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Notepadqq...'
  show_warning 'Requires root privileges'
  sudo apt install -y notepadqq
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
