#!/bin/bash

# Minecraft
function minecraft {
	# Add repository
	show_info 'Adding Minecraft PPA to software sources...'
	show_warning 'Requires root privileges'
	sudo add-apt-repository -y ppa:minecraft-installer-peeps/minecraft-installer
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing Minecraft...'
	show_warning 'Requires root privileges'
	sudo apt install -y minecraft-installer
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
