#!/bin/bash

# Scribus
function scribus {
	# Add the Scribus repository signing key to be able to verify downloaded packages
	show_info 'Adding Scribus signing key to keyring...'
	show_warning 'Requires root privileges'
	gpg --keyserver wwwkeys.pgp.net --recv-keys EEF818CF
  gpg --armor --export EEF818CF | sudo apt-key add -
	show_success 'Done.'
	# Add the Scribus repository
	show_info 'Adding Spotify repository to software sources...'
	show_warning 'Requires root privileges'
  sudo sh -c 'echo "deb http://debian.scribus.net/debian/ stable main" >> /etc/apt/sources.list.d/scribus.list'
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing Scribus...'
	show_warning 'Requires root privileges'
	sudo apt install scribus-ng
	# Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
