#!/bin/bash

# Typecatcher
function typecatcher {
  # Add repository
  show_info 'Adding LibreOffice PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:andrewsomething/typecatcher
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt update
  # Install
  show_info 'Installing Typecatcher...'
  show_warning 'Requires root privileges'
  sudo apt install -y typecatcher
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
