#!/bin/bash

# Poppy OS X Cursors X11 Mouse Theme
function poppy-mac-cursor {
  show_info 'Downloading Poppy OS X Cursors X11 Mouse Theme...'
  wget http://orig01.deviantart.net/66bb/f/2016/134/0/f/poppy_os_x_cursors_1_3_0_by_kayover-da2eu1h.zip
  # Install package(s)
  show_info 'Installing Poppy OS X Cursors X11 Mouse Theme...'
  unzip poppy*.zip
  cd Poppy-OS-X-Cursors
  sudo mkdir /usr/share/icons/Poppy-OS-X-Cursors
  sudo cp -rf cursors index.theme /usr/share/icons/Poppy-OS-X-Cursors
  sudo update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme /usr/share/icons/Poppy-OS-X-Cursors/index.theme 90
  # Back
  cd -
  # Cleanup and finish
  rm poppy*.zip
  # Apply
  show_info 'Apply Theme...'
  gsettings set org.gnome.desktop.interface cursor-theme 'OSX-ElCap'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
  }
