#!/bin/bash

# Paper Icon Theme
function paper-icon {
  # Add repository
  show_info 'Adding Paper PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:snwh/pulp
  # Update repository information
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update
  # Install
  show_info 'Installing Paper...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y paper-icon-theme
  # Apply
  show_info 'Apply Icon Theme...'
  gsettings set org.gnome.desktop.interface icon-theme 'Paper'
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty-theme
}
