#!/bin/bash

# Atom
function atom {
  show_info 'Downloading Atom...'
  # Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        show_info 'No packages available to download that matches your system...'
	        ;;
	    x86_64)
	        wget https://atom-installer.github.com/v1.9.8/atom-amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  # Install dependencies
  show_info 'Installing Atom dependencies...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y gconf2 gconf-service git libgtk2.0-0 libudev1 libgcrypt20 libnotify4 libxtst6 libnss3 python gvfs-bin xdg-utils libcap2
  # Install package(s)
  show_info 'Installing Atom...'
  show_warning 'Requires root privileges'
  sudo dpkg -i atom*.deb
  sudo apt-get install -fy
  # Cleanup and finish
  rm atom*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
