#!/bin/bash

# Brackets
function brackets {
  show_info 'Downloading Brackets...'
  # Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        wget --referer=https://github.com/adobe/brackets/releases/download/release-1.6%2Beb4/Brackets.1.6.Extract.32-bit.deb https://github.com/adobe/brackets/releases/download/release-1.6%2Beb4/Brackets.1.6.Extract.32-bit.deb
	        ;;
	    x86_64)
	        wget --referer=https://github.com/adobe/brackets/releases/download/release-1.6%2Beb4/Brackets.1.6.Extract.64-bit.deb https://github.com/adobe/brackets/releases/download/release-1.6%2Beb4/Brackets.1.6.Extract.64-bit.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  # Install dependencies
  show_info 'Installing Brackets dependencies...'
  show_warning 'Requires root privileges'
  sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libfreetype6 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk2.0-0 libnspr4 libnss3 libpango1.0-0 libstdc++6 libx11-6 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxrender1 ca-certificates libcurl3 lsb-base xdg-utils wget
  # Fix shared libraries error for 'libgcrypt.so.11'
  show_info "Downloading package to provide missing 'libgcrypt.so.11'..."
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O https://launchpadlibrarian.net/201289903/libgcrypt11_1.5.3-2ubuntu4.2_i386.deb
	        ;;
	    x86_64)
	        curl -O https://launchpadlibrarian.net/201289896/libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
  show_info "Installing 'libgcrypt11'..."
  show_warning 'Requires root privileges'
  sudo dpkg -i libgcrypt11*.deb
  sudo apt-get install -fy
  # Cleanup and finish
  rm libgcrypt11*.deb
  # Install package(s)
  show_info 'Installing Brackets...'
  show_warning 'Requires root privileges'
  sudo dpkg -i Brackets*.deb
  sudo apt-get install -fy
  # Cleanup and finish
  rm Brackets*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  thirdparty
}
