#!/bin/bash

# Alsa tools
function alsa {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing Alsa tools...'
	show_warning 'Requires root privileges'
	sudo apt install -y alsa-base alsa-utils
	# Done
	show_success 'Done.'
	whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
