#!/bin/bash

# ext4 tools
function ext4 {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing ext4 tools...'
	show_warning 'Requires root privileges'
	sudo apt install -y e2fslibs e2fsprogs
	# Done
	show_success 'Done.'
	whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
