#!/bin/bash

# VPN
function vpn {
	# Update repository information
	show_info 'Updating repository information...'
	show_warning 'Requires root privileges'
	sudo apt update
	# Install
	show_info 'Installing VPN tools...'
	show_warning 'Requires root privileges'
	sudo apt install -y openvpn easy-rsa
	# Done
	show_success 'Done.'
	whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
