#!/bin/bash

	# I
	case `echo sudo df -h` in
	    /)
	        curl -O https://tlgrm.ru/files/locales/tdesktop/Russian.strings
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;; 
	esac	

function speedup {
    eval `resize`
    CONF=$(whiptail \
        --notags \
        --title "Speed up system" \
        --menu "\nWhat would you like to do?" \
        --ok-button "Apply" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        xorg        'Xorg' \
        tmpfs       'tmp on tmpfs (need reboot)' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $CONF
    else
        clear && main
    fi
}
