#!/bin/bash

# GitKraken
function gitkraken {
	show_info 'Downloading GitKraken...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O https://release.gitkraken.com/linux/gitkraken-i386.deb
	        ;;
	    x86_64)
	        curl -O https://release.gitkraken.com/linux/gitkraken-amd64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing GitKraken...'
	show_warning 'Requires root privileges'
	sudo dpkg -i gitkraken*.deb
	sudo apt install -fy
	# Cleanup and finish
	rm gitkraken*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
