#!/bin/bash

# Haroopad
function haroopress {
	show_info 'Downloading Haroopad...'
	# Download Debian file that matches system architecture
	case `uname -i` in
	    i386|i486|i586|i686)
	        curl -O https://bitbucket.org/rhiokim/haroopad-download/downloads/haroopad-v0.13.1-ia32.deb
	        ;;
	    x86_64)
	        curl -O https://bitbucket.org/rhiokim/haroopad-download/downloads/haroopad-v0.13.1-x64.deb
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac
	# Install package(s)
	show_info 'Installing Haroopad...'
	show_warning 'Requires root privileges'
	sudo dpkg -i haroopad*.deb
	sudo apt install -fy
	# Cleanup and finish
	rm haroopad*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
