#!/bin/bash

# Smartgit
function smartgit {
	show_info 'Downloading Smartgit...'
	# Download Debian file that matches system architecture
  curl -O http://www.syntevo.com/smartgit/download?file=smartgit/smartgit-7_0_4.deb
	# Install package(s)
	show_info 'Installing Smartgit...'
	show_warning 'Requires root privileges'
	sudo dpkg -i smartgit*.deb
	sudo apt-get install -fy
	# Cleanup and finish
	rm smartgit*.deb
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
