#!/bin/bash

# Ubuntu make
function umake {
  # Add repository
  show_info 'Adding Ubuntu make PPA to software sources...'
  show_warning 'Requires root privileges'
  sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make
	# Update repository information
	show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
	sudo apt update
	# Install
  show_info 'Installing Ubuntu make...'
  show_warning 'Requires root privileges'
  sudo apt install -y ubuntu-make
  # Done
  show_success 'Done.'
  # Install Android Studio
  show_info 'Installing Android Studio...'
  umake android
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}
